name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.OMKAR }}
          script: |
            cd /home/ubuntu/skillsbridge/project/Backend
            git pull origin main
            source venv/bin/activate
            TMPDIR=~/pip-tmp pip install -r requirements.txt
            sudo systemctl restart flaskapp
